### ISSUE TITLE
Syntax highlighting for HTML files

### ISSUE THREAD

**Issue by joshamaju** [sublimelsp/LSP-svelte#111]
How can I enable Svelte syntax highlighting for HTML files using LSP-svelte.

I've tried using the Svelte package, but it doesn't show up int the package settings just like LSP language server and other packages show up

<img width="1160" alt="Screenshot 2023-08-12 at 18 57 52" src="https://github.com/sublimelsp/LSP-svelte/assets/127889846/4a2aaa4f-a25b-4d19-8d2e-7f1586a6e099">

<img width="634" alt="Screenshot 2023-08-12 at 18 59 19" src="https://github.com/sublimelsp/LSP-svelte/assets/127889846/797ba687-fc1a-44e0-bafc-3b19a8cf5de1">

**Comment by predragnikolic** [comment]
Hello,

To answer your question,
Select `View > Syntax > Open all with current extension as... > Svelte`

**Comment by joshamaju** [comment]
Thank you 🙏🏼, that solved it
