### ISSUE TITLE
How to disable argument wrap

### ISSUE THREAD

**Issue by gavalierm** [sublimelsp/LSP-svelte#122]
from 

```
      <button
        on:click={onSendMessage}
        value={" ADDR " + command.path + " " + 1}
        class="on"
      >
```

to 

```
      <button on:click={onSendMessage} value={" ADDR " + command.path + " " + 1} class="on" >
```

thank you

**Comment by predragnikolic** [comment]
Hello @gavalierm,

I am not sure on how to tell the svelte lanuage server on how to format code,
It would be better to ask that question here https://github.com/sveltejs/language-tools.

I will close the issue, but if you have any question feel free to ping me.
