### ISSUE TITLE
Crash with Svelte 5 

### ISSUE THREAD

**Issue by blackjyn** [sublimelsp/LSP-svelte#129]
So, Svelte 5 is now at RC. then I tried some taste of it.

I add v5 my project:
```
λ npm install --save-dev svelte@next
λ npm list
root-js-svelte5rc@0.0.1 SvelteNEXT
├── @sveltejs/adapter-auto@3.2.0
├── @sveltejs/kit@2.5.7
├── @sveltejs/vite-plugin-svelte@3.1.0
├── svelte-check@3.7.0
├── svelte@5.0.0-next.120
├── typescript@5.4.5
└── vite@5.2.10
```

then Sublime Text triggers: 
![svelte5_lsp_error](https://github.com/sublimelsp/LSP-svelte/assets/6046191/b88cd5a0-2ef0-4c38-8b12-da94bae78612)

Then the LSP log : 
```
LSP-svelte: Error: Cannot find module 'D:\xxxx\_SvelteNEXT\node_modules\svelte\compiler.cjs
```
And yes, Svelte 5 deosnt have that compiler.cjs file.

Svelte 4 running just fine.

ENV: 
- WIndows x64
- Sublime Text 4
- LSP Svelte v3,10

**Comment by predragnikolic** [comment]
I will try to find time to see how to address this.

Thanks for the report.

**Comment by predragnikolic** [comment]
this PR is related https://github.com/sveltejs/language-tools/pull/2327

**Comment by predragnikolic** [comment]
I created a release which includes the fix https://github.com/sublimelsp/LSP-svelte/releases/tag/v3.1.1
it will be available in ~2h or less on Package Control

**Comment by blackjyn** [comment]
wohoo, Svelte 5 support works like a charm . Thank you @predragnikolic 
![svelte5lsp](https://github.com/sublimelsp/LSP-svelte/assets/6046191/9c01bc00-02d4-4052-8581-d986e7eb6b21)
