### ISSUE TITLE
code actions lag

### ISSUE THREAD

**Issue by basaran** [sublimelsp/LSP-svelte#54]
hi, can I send a PR for the README to include .tsconfig.json ? Without it, the `code actions` enabled is causing lag during file save.

**Comment by basaran** [comment]
well, it seems the lag was due to node process roofing up due to scss compilation.

**Comment by basaran** [comment]
would there be a way to exclude LSP from compiling SCSS ? I tried .eslintignore but that didn't do anything. 

Should I create an issue with the upstream? SCSS compilation is beneficial for small scss, but if you are importing a large file (such as a theme), it brings the language server down with timeouts, not to mention the CPU usage combined together with the dev server compiling on its own.

**Comment by rwols** [comment]
Yes, try opening an issue for it at https://github.com/sveltejs/language-tools/issues

**Comment by basaran** [comment]
I did, closing here. https://github.com/sveltejs/language-tools/issues/1117
