### ISSUE TITLE
How to configure compilerWarnings in .sublime-project?

### ISSUE THREAD

**Issue by andremacola** [sublimelsp/LSP-svelte#56]
I tried everything in LSP standard documentation.

Is this correct?

```json
"settings": {
    "LSP": {
        "LSP-svelte": {
            "initializationOptions": {
                "configuration": {
                    "svelte": {
                        "plugin": {
                            "svelte": {
                                "compilerWarnings": {
                                    "css-unused-selector": "ignore",
                                    "a11y-invalid-attribute": "ignore",
                                    "a11y-missing-attribute": "ignore"
                                }
                            }
                        }
                    }
                }
            }
        },
    },
}

```

**Comment by ihodex** [comment]
@andremacola Hello :)

Use `Preferences › Package Settings › LSP › Servers › LSP-svelte` settings

**Comment by TehShrike** [comment]
I am following the template in the default LSP-Svelte settings, but my ignored compiler warnings are not being respected.

```json
{
	"initializationOptions": {
		"configuration": {
			"svelte": {
				"plugin": {
					"svelte": {
						"compilerWarnings": {
							"a11y-label-has-associated-control": "ignore"
						}
					}
				}
			}
		}
	}
}
```

I still see `a11y-label-has-associated-control` warnings in my Svelte files, even after restarting the LSP server.

**Comment by ArtskydJ** [comment]
> I updated my user `LSP-Svelte.sublime-settings` file following the template in the default LSP-Svelte settings, but my ignored compiler warnings are not being respected.
> 
> ...
> 
> I still see `a11y-label-has-associated-control` warnings in my Svelte files, even after restarting the LSP server.

Weird, your config works for me in my global `Packages/User/LSP-svelte.sublime-settings`.

And this config worked for me in my `repo/main.sublime-project`
https://github.com/sublimelsp/LSP-svelte/issues/56#issuecomment-896756623
