### ISSUE TITLE
Package not showing on Linux?

### ISSUE THREAD

**Issue by jatinhemnani01** [sublimelsp/LSP-svelte#58]
![sublime](https://user-images.githubusercontent.com/73883835/129487763-f4950bf8-edd9-4dd9-9980-c7eb86ed36d4.gif)

**Comment by rchl** [comment]
Do you see it in the "Remove Package" list?

**Comment by jatinhemnani01** [comment]
Nope but I cloned the repo and it works great. I think it something with my system some packages doesn't show

**Comment by ihodex** [comment]
Paste your `ST` (`Preferences › Settings`) and `Package Control` (`Preferences › Package Settings › Package Control › Settings`)  settings :)

**Comment by jatinhemnani01** [comment]
```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"BracketHighlighter",
		"Emmet",
		"FileIcons",
		"Git",
		"LSP",
		"Package Control",
		"React IDE",
		"SideBarEnhancements",
		"Svelte",
		"Terminus",
		"Theme - Cobalt2",
		"TypeScript",
	],
}

```
