### ISSUE TITLE
aliases inside svelte components

### ISSUE THREAD

**Issue by basaran** [sublimelsp/LSP-svelte#61]
Hello, thank you for the package.

I'm trying to setup go to definition for my aliases inside svelte components:

```
<style lang="scss">
@import "@css/mixins/media-queries.scss";
..
</style>
```

I have the following in my jsconfig and tsconfig:

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@css": ["src/css"],
            "@css/*": ["src/css/*"],
        }
    },
    "include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.svelte", "src/**/*.css", "src/**/*.scss"],
    "exclude": ["node_modules", "**/node_modules", "dist"]
}
```

but when I try to go to definition, sublime says nothing was found. Is there a setting I can use with the LSP config for this?

**Comment by istudyatuni** [comment]
Hello! This now works for me in the `script` tag. My jsconfig:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "src/*": ["./src/*"]
    }
  }
}
```

and inside the component

```svelte
<script context="module">
    import { testData } from 'src/stores/test'
</script>
````

a hover with information is displayed. But it doesn't works when importing a component into a component (except auto-completing props names)

```svelte
<script context="module">
    import SideMenu from 'src/components/organisms/SideMenu'
</script>
```

But! It not works in VS Code too (I think we can use this as a benchmark)

**Comment by predragnikolic** [comment]
Hello, 
There is nothing that can be implemented in this repo to achieve your feature request, so I will close this issue.

I would advice you to open a feature request at https://github.com/sveltejs/language-tools.

**Comment by predragnikolic** [comment]
Just to be clear, path aliasing works for components.
<img width="1486" alt="Screenshot 2022-08-01 at 12 37 37" src="https://user-images.githubusercontent.com/22029477/182130614-e81deb0c-b43c-49b7-9599-6771a5689f1c.png">

But go to definition will not work for this css/scss files:
```
<style lang="scss">
@import "@css/mixins/media-queries.scss";
..
</style>
```

**Comment by basaran** [comment]
Thank you for the clarification.
