### ISSUE TITLE
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer

### ISSUE THREAD

**Issue by easyfrog** [sublimelsp/LSP-svelte#90]
I got these errors:

The error occurs on node 18.7.0 but  works  fine on node 10.16.0 and 16.8.0

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/10724325/192153854-0371f206-531c-4fc1-912e-48db8e5206e4.png">

**Comment by rchl** [comment]
Likely that https://github.com/sveltejs/language-tools is not compatible with Node 18. You can create an issue in https://github.com/sveltejs/language-tools

On our side we could implement a check for "too new" node version and show some more user friendly error in this case. There is a feature request for it already in https://github.com/sublimelsp/lsp_utils/issues/89

**Comment by predragnikolic** [comment]
@easyfrog to add on @rchl note.

One way to avoid hitting this issue and having to manually switch to node versions is to:
1. Open the command palette and select `Preferences: LSP Utils Settings`,
2. and modify the following setting:
```
{
    "nodejs_runtime": ["local"],
}
```
that will prompt you to install a local node version in Sublime Packages Folder(you do not need to know that). 
That local node version will not affect your system. 
LSP-* node based plugins will use that local node version, and thus you will not see this error anymore.

**Comment by easyfrog** [comment]
I view the codes in the error place. `read-wasm.js` first line.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/10724325/192281345-13be711a-6bc3-4cfb-9715-bdd943141c7d.png">

I think the error because node 18 support `fetch` api, but there is not `mappingsWasmUrl` supply. 
So  I simply change the fist line to `if (false)` to avoid using `fetch` api. 😄
